[v1]
"soros-bench-tps 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/bench-tps)" = ["soros-bench-tps"]
"soros-drone 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/drone)" = ["soros-drone"]
"soros-fullnode 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/fullnode)" = ["soros-fullnode"]
"soros-genesis 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/genesis)" = ["soros-genesis"]
"soros-gossip 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/gossip)" = ["soros-gossip"]
"soros-install 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/install)" = ["soros-install"]
"soros-keygen 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/keygen)" = ["soros-keygen"]
"soros-ledger-tool 0.14.0 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/ledger-tool)" = ["soros-ledger-tool"]
"soros-wallet 0.14.2 (path+file:///home/ben/Downloads/bus/vendor/rustelo-rust/soros/wallet)" = ["soros-wallet"]
