[package]
name = "buffett-fullnode-config"
version = "0.1.0"
authors = ["Caesar Chad <BLUE.WEB.GEEK@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
dirs = "1.0.2"
serde_json = "1.0.10"
buffett-core = "0.1.1"
buffett-crypto ="0.1.1"