[package]
name = "buffett-metrics"
version = "0.1.3"
authors = ["Caesar Chad <BLUE.WEB.GEEK@gmail.com>"]
edition = "2018"
description= "Dashboard for bitconch:buffett"
license = "MIT"

[dependencies]
buffett-timing = "0.1.1"
influx_db_client = "0.3.4"
sys-info = "0.5.6"
log="0.4.2"