[package]
name = "buffett-genesis"
version = "0.1.0"
authors = ["Caesar Chad <BLUE.WEB.GEEK@gmail.com>"]
edition = "2018"

[dependencies]
atty = "0.2"
clap = "2.32"
serde_json = "1.0.10"
buffett-core = "0.1.1"